version: "3.9"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  app2:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:root1@db/db_pokemon
volumes:
  db_data:
